[en]
    weight          = 1
    languageCode    = "en"
    languageName    = "English"
    contentDir      = "content/en"
    # To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
    copyright       = "&copy; The Point. Powered by [Pantrypoints](https://pantrypoints.com)"
    # The title of site
    title           = "The Point | News that Gets to the Point"

    [en.params]
        author = "The Point"
        # keywords = "Superphysics, Physics, Economics, Metaphysics"
        description = "The Point is a concise news site for busy people who needs the important details fast"

[tl]
    weight          = 2
    languageCode    = "tl"
    languageName    = "Tagalog"
    contentDir      = "content/tl"
    copyright       = "&copy; The Point. Mula sa [Pantrypoints](https://pantrypoints.com)"
    title           = "The Point | Diretso sa Punto"

    [tl.params]
        author = "Pantry Peers"
        # keywords = "Hugo-Bulma, Hugo, Bulma, 主题"
        description = "The Point is a concise news site for busy people who needs the important details fast"


[vi]
    weight          = 3
    languageCode    = "vi"
    languageName    = "Tieng Viet"
    contentDir      = "content/vi"
    copyright       = "&copy; The Point. [Pantrypoints](https://pantrypoints.com)"
    title           = "The Point"

    [vi.params]
        author = "Pantry Peers"
        # keywords = "Hugo-Bulma, Hugo, Bulma, 主题"
        description = "The Point is a concise news site for busy people who needs the important details fast"
