[en]
    weight          = 1
    languageCode    = "en"
    languageName    = "English"
    contentDir      = "content/en"
    # To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
    copyright       = "&copy; The Point. Powered by [Pantrypoints](https://pantrypoints.com)"
    # The title of site
    title           = "The Point Commmunity-sourced News"

    [en.params]
        author = "The Point"
        # keywords = "Superphysics, Physics, Economics, Metaphysics"
        description = "The Point is a news site for articles submitted by the community"

[tl]
    weight          = 2
    languageCode    = "tl"
    languageName    = "Tagalog"
    contentDir      = "content/tl"
    copyright       = "&copy; The Point. Powered by [Pantrypoints](https://pantrypoints.com)"
    title           = "The Point Balita Mula sa Komunidad"

    [tl.params]
        author = "Pantry Peers"
        # keywords = "Hugo-Bulma, Hugo, Bulma, 主题"
        description = "The Point is a news site for articles submitted by the community"
